import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { DrawerDemo } from '@/components/drawer'
import { db } from '@/lib/db';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getProfessores = () => {
  return db.professores.findMany()
}


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const professores = await getProfessores()
  return (
    <html lang="en">
      <body className={`${inter.className} bg-stone-200`}>
        <main className="m-auto grid w-full max-w-xl relative grid-rows-[fit-content(100%)_auto] min-h-[100dvh]">
          {children}
          <DrawerDemo professores={professores} />
        </main>
      </body>
    </html>
  );
}
